; $Id: makefile.txt,v 1.1 2002-04-15 16:37:50 ktk Exp $ 


NMAKE targets for the Netlabs EPM Distribution package
------------------------------------------------------

NOTE:  edit configure.in to your needs before executing (n)make

make all     - build complete package

make inst    - build complete package and start WPI
make show    - build NEPMD INF and show it

make prepare - only downloads zip files from leo and unpacks
make check   - check prepared files for zero byte files, making WIC trap
               (thanks god !). I had some zero byte files from time to time,
               maybe pkunzip2 does not work properly
