
NMAKE targets for the Netlabs EPM Distribution package
------------------------------------------------------

make all     - build complete package (*)

make inst    - build complete package and start WPI (*)

make nepmd   - build NEPMD extensions
make srccopy - copy some NEPMD files directly from CVS tree part to compile directory
make show    - build NEPMD INF and show it

make prepare - only downloads EPMBBS zip files from leo and unpacks (*)
make check   - check prepared files for
               - SYSxxxx errors during unpack
               - zero byte files, making WIC trap (thanks god !).
                 pkunzip2 does not unpack properly sometimes (zero byte files)

NOTE:
- edit configure.in to your needs before executing (n)make
- targets marked with (*) require a working intenet connection
  for to download the EPM packages, if not already done
