.. ***************************** Module Header *******************************
..
.. Module Name: makefile.txt
..
.. source file for the INF file providing help for makefile
.. Requires HyperText/2 package to compile
..
.. Unlike the nepmd.inf, the makfile.inf is compiled to the bin subdirectory
.. and checked in to make it always available right after checking out.
..
.. So when updating this file, commit also the changed INF file !!!
..
.. Copyright (c) Netlabs EPM Distribution Project 2002
..
.. $Id: makefile.txt,v 1.7 2002-06-04 23:23:12 cla Exp $
..
.. ===========================================================================
..
.. This file is part of the Netlabs EPM Distribution package and is free
.. software.  You can redistribute it and/or modify it under the terms of the
.. GNU General Public License as published by the Free Software
.. Foundation, in version 2 as it comes in the "COPYING" file of the
.. Netlabs EPM Distribution.  This library is distributed in the hope that it
.. will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
.. of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.. General Public License for more details.
..
.. ***************************************************************************

.hi 234
.include title.inc
.set TITLE=*[=DOCTITLE]*

.set STDLIST=compact break=fit tsize=20

.ti [=DOCTITLE]

.. =============================================================================
.1 Making of [=DOCTITLE]
.. =============================================================================
.an IDPNL_OVERVIEW
.
.at font='20.Tms Rmn' fc=darkgray italic bold
.bitmap src\bmp\nllogo.bmp center
.ce present the Making of
.at font='24.Tms Rmn' fc=red bold italic
.ce The [=DOCTITLE]
.at

[=TOPICS]
.su 1

.. -----------------------------------------------------------------------------
.2 makefile pseudotargets
.. -----------------------------------------------------------------------------
.an IDPNL_TARGETS
.
[=TOPICS]
.su V30

.. .............................................................................
.3 main makefile
.. .............................................................................
.an IDPNL_TARGETS_MAIN
.
The following makefile targets are available for the main makefile within the project
working directory (root of the development tree):
.pl bold compact break=none tsize=20
- nmake
= show this INF file (if outdated, this compiles the INF before). This calls the
  makefile within the *src\ipf* directory with the target *help*.
.
- nmake clean
= remove the *compile* and binary (both *debug* and *release*) directories
.
- nmake all
= build all modules and thus the complete package (**)
.
  This is achieved ba calling all makefiles below the *src* subdirectory, of which
  the subdirectories are listed in the macro *MODULELIST*
.
  This results in the *WarpIn* WPI package file created
  either in the *debug* or *release* directory, depending on the value of 
  the *DEBUG* environment variable (**)
.
- nmake inst
= like *nmake all*, but also starts the WPI file (**)
.
- nmake show
= build NEPMD INF and show it

[=NOTE]
.ul compact
- edit configure.in to your needs before executing nmake
- targets marked with (**) require a working internet connection
  for to download the EPM packages, if they are not available within the directory
  specified by the macro *ZIPSRCDIR* in the file *configure.in*.

.. .............................................................................
.3 ipf\makefile
.. .............................................................................
.an IDPNL_TARGETS_IPF
.
The following makefile targets are available for the makefile within the
*src\ipf* subdirectory:
.pl bold compact break=none tsize=20
- nmake [[all]]
= build both the makefile INF and the project documentation INF, but show none
.
- nmake help
= build and show this INF file (if outdated, this compiles the INF before). This is used
  by the [.IDPNL_TARGETS_MAIN main makefile] in order to bring up help if called with no
  target specified
.
- nmake helpinf
= build this makefile in the *bin* subdirectory !
- nmake nepmdinf
= build the project documentation INF in the *compile\netlabs\book directory*
.
- nmake clean
= remove the files created by this makefile. See the macro *FILESTOCLEAN* for a complete list.
.
 [=NOTE]
.ul compact
  - directories are not removed by this pseudotarget. For a complete cleanup, call
    *nmake clean* within the project working directory (root of the development tree).

.. .............................................................................
.3 rexx\makefile
.. .............................................................................
.an IDPNL_TARGETS_REXX
.
The following makefile targets are available for the makefile within the
*src\rexx* subdirectory:
.pl bold compact break=none tsize=20
- nmake [[all]]
= create NLSETUP.EXE in the *compile\netlabs\install directory*  
.
- nmake clean
= remove the file created by this makefile. See the macro *FILESTOCLEAN* for a complete list.
.
 [=NOTE]
.ul compact
  - directories are not removed by this pseudotarget. For a complete cleanup, call
    *nmake clean* within the project working directory (root of the development tree).

.. .............................................................................
.3 netlabs\makefile
.. .............................................................................
.an IDPNL_TARGETS_NETLABS
.
The following makefile targets are available for the makefile within the
*src\netlabs* subdirectory:
.pl bold compact break=none tsize=20
- nmake [[all]]
= copy all modified files below the *src\netlabs* directory to the *compile\netlabs* directory
.
- nmake checksrc
= check only if some files have been modified. If not, the flag file *compile\srccopy.txt*
  is created, otherwise it is deleted.
- nmake srccopy
= copy modified files anyway
.
- nmake clean
= remove the flag file created by this makefile. See the macro *FILESTOCLEAN* for a complete list.
.
 [=NOTE]
.ul compact
  - directories are not removed by this pseudotarget. For a complete cleanup, call
    *nmake clean* within the project working directory (root of the development tree).

.. .............................................................................
.3 wis\makefile
.. .............................................................................
.an IDPNL_TARGETS_WIS
.
.at hi
[=NOTE]
.ul compact
- This makefile has to be called last, as it it relies on the files created and 
  copied by the other makefiles from within the *src* directory tree to the
  temporary *compile* and *debug* or *release* subdirectories.
  In order to make sure that everyhing is processed in the correct order, process
  the main makefile by executing
.sl compact
  -  nmake all
.el
 in the project working root directory instead.
.at

The following makefile targets are available for the makefile within the
*src\wis* subdirectory:
.pl bold compact break=none tsize=20
- nmake [[all]]
= downloads and unpacks files from leo and build complete package.
  This results in the *WarpIn* WPI package file created
  either in the *debug* or *release* directory, depending on the value of 
  the *DEBUG* environment variable (**)
.
- nmake inst
= like *nmake all*, but also starts the WPI file (**)
.
- nmake prepare
= only downloads EPMBBS zip files from leo and unpacks (**)
- nmake check
= check prepared files for
.ul compact
  - SYSxxxx errors during unpack
  - zero byte files, making WIC trap (thanks god !).
    pkunzip2 does not unpack properly sometimes (zero byte files)
.el
.
- nmake clean
= remove the flag file created by this makefile. See the macro *FILESTOCLEAN* for a complete list.
.
 [=NOTE]
.ul compact
  - directories are not removed by this pseudotarget. For a complete cleanup, call
    *nmake clean* within the project working directory (root of the development tree).

[=NOTE]
.ul compact
- edit configure.in to your needs before executing nmake
- targets marked with (**) require a working internet connection
  for to download the EPM packages, if they are not available within the directory
  specified by the macro *ZIPSRCDIR* in the file *configure.in*.


.. -----------------------------------------------------------------------------
.2 Requirements
.. -----------------------------------------------------------------------------
.an IDPNL_REQUIREMENTS
.
The following is required for making [=TITLE]:
.su V30

.. .............................................................................
.3 WarpIn
.. .............................................................................
.an IDPNL_REQUIREMENTS_WARPIN
.
The *WarpIn* Installer is used to create the installation package.
As a minimum version 0.9.18 is required.

[=NOTE]
.ul compact
- You can download *Warpin* from
  - [http://www.xworkplace.org]
- makefile processing will extend the environment automatically
  to access the *WarpIn* executables, so it is not required to make
  them accessible via the PATH statement.

.. .............................................................................
.3 C Compiler
.. .............................................................................
.an IDPNL_REQUIREMENTS_COMPILER
.
As compiler the following are supported
.ul compact
- *IBM CSet /2* (debugger seems not to cope with the debug version...)
- *IBM VAC 3.08* (much better debugger)

[=NOTE]
.ul compact
- the compiler used is automatically recognized by the makefile

.. .............................................................................
.3 Toolkit for OS/2 Warp
.. .............................................................................
.an IDPNL_REQUIREMENTS_TOOLKIT
.
As toolkit one of the following is required:
.ul compact
- *OS/2 Warp 3 Developers Toolkit*
- *OS/2 Warp 4 Developers Toolkit*
- *OS/2 Warp 4.5 Developers Toolkit*

.. .............................................................................
.3 PKUNZIP2
.. .............................................................................
.an IDPNL_REQUIREMENTS_PKUNZIP2
.
PKUNZIP2 is required in order to unpack certain parts of the EPMBBS packages,
as it supports the shrink method, this is not supported by newer versions of *Info-Zip*.

As PKUNZIP2.EXE comes as part of *MPTS*, it is available on OS/2 Warp Systems with
Network or Internet Access Kit installed.

.. .............................................................................
.3 unzip.exe of Info-Zip
.. .............................................................................
.an IDPNL_REQUIREMENTS_UNZIP2
.
UNZIP is required in order to unpack certain parts of the EPMBBS packages,
as it supports the "deflated" method used for some text files, this is not supported by 
PKUNZIP2.

[=NOTE]
.ul compact
- You can download *unzip* from
  - [http://www.info-zip.org Info-ZIP's homepage (www.info-zip.org)]
- *unzip.exe* must be accessible by the PATH statement

.. .............................................................................
.3 wget
.. .............................................................................
.an IDPNL_REQUIREMENTS_WGET
.
*wget* is used to download of the original zip files, if not present   
(currently tested with wget v1.7).

[=NOTE]
.ul compact
- You can download *wget* from 
  - [http://hobbes.nmsu.edu/cgi-bin/h-search?key=wget The Hobbes File Archive]
.
    (search "wget" at hobbes.nmsu.edu)
- *wget.exe* must be accessible by the PATH statement
- when sitting behind a firewall, create/modify a wget resource file in order
  to use an FTP proxy. Insert or add the following entries to the file
  %home%\.wgetrc and replace the bold printed values as required:
.fo off
       ftp__proxy=http://*proxyname*:*proxyport*
       proxy__user=*proxy__userid*
       proxy__passwd=*proxy__password*
.fo on

.. .............................................................................
.3 HyperText/2
.. .............................................................................
.an IDPNL_REQUIREMENTS_HTEXT
.
For compilation of the online help the pÅreprocessor *HyperText/2* is used.

[=NOTE]
.ul compact
- You can download *HyperText/2* from 
  - [http://hobbes.nmsu.edu/cgi-bin/h-search?key=htext The Hobbes File Archive]
.
    (search "htext" at hobbes.nmsu.edu)
- install according to the information in htext.inf
  - *htext.cmd* must be accessible by the PATH statement
  - the bitmap files ***.bmp* must be placed either
    - into the same directory where you put *htext.cmd* to
    - into a subdirectory *htext* within the directory where you
      put *htext.cmd* to
    - into a directory specified in the environment variables
      - *INCLUDE*
      - *HTINCLUDE*

.. .............................................................................
.3 GREP
.. .............................................................................
.an IDPNL_REQUIREMENTS_GREP
.
For checking unpacked EPM files the *grep* utility is used.

[=NOTE]
.ul compact
- You can download *Grep v2.0* from 
  - [http://hobbes.nmsu.edu/cgi-bin/h-search?key=grep20 The Hobbes File Archive]
.
    (search "grep20" at hobbes.nmsu.edu)
- *grep.exe* must be accessible by the PATH statement

.. .............................................................................
.3 REXX2EXE
.. .............................................................................
.an IDPNL_REQUIREMENTS_REXX2EXE
.
For converting a REXX script to an executable the *REXX2EXE* compiler us used.

[=NOTE]
.ul compact
- You can download *REXX2EXE* from 
  - [http://hobbes.nmsu.edu/cgi-bin/h-search?key=rexx2exe The Hobbes File Archive]
.
    (search "rexx2exe" at hobbes.nmsu.edu)
- *rexx2exe.exe* must be accessible by the PATH statement

.. .............................................................................
.3 FASTDEP
.. .............................................................................
.an IDPNL_REQUIREMENTS_FASTDEP
.
For creating dependency files the FastDep utility is used.

[=NOTE]
.ul compact
- You can download *FastDep* from the *OS/2 Netlabs Archive* of the *XWorkplace* project.
- *fastdep.exe* must be accessible by the PATH statement

.. -----------------------------------------------------------------------------
.2 CVS development tree overview
.. -----------------------------------------------------------------------------
.an IDPNL_DEVTREE
.
The following directories currently exist in the CVS development tree
.
(the *CVS* maintenance directories are not included here):
.pl compact break=none tsize=15
.fo off
<working dir>
√ƒheader       GNU header for all used filetypes
√ƒipf          HypeText/2 sources for the NEPMD INF files
≥ ¿ƒbmp        bitmaps for INF files
√ƒ[=DISTDIR]      base directory for sources simoly copied to compile\[=DISTDIR]
≥ ¿ƒinstall    installation related files
≥     ¿ƒico    NEPMD related icons for installation
√ƒrexx         REXX sources being compiled for NEPMD
¿ƒwis          WarpIn script
.fo on

The following _temporary_ directory trees are created when building the *WarpIn* package:
.fo off
<working dir>
√ƒcompile      holds temporary files being the same for debug or
≥  ≥           release version
≥  ¿ƒ[=DISTDIR]   directory tree to be packed into the WarpIn package
≥    ¿ƒinstall holding copies of files of src\[=DISTDIR]
≥      ¿ƒico   or compiled binaries
≥
¿ƒ<binary dir> the name of this directory is either *debug* or *release*
   ≥           Among others it holds the resulting WarpIn package file.
   ¿ƒ[=DISTDIR]   directory tree to be packed into the WarpIn package
     ¿ƒbin     holding copies of selected executables being compiled to
               <binary dir>
.fo on

[=NOTE]
.ul compact
- the temporary directory trees can be completely cleaned up (deleted) with
  executing *nmake clean* in the working root directory.

.. -----------------------------------------------------------------------------
.2 configuring the makefile
.. -----------------------------------------------------------------------------
.an IDPNL_CONFIGMAKE
.
The *makefile* requires several lists values, of which some have to be configured
before executing *nmake*.

_*values to be configured by everybody*_
.pl bold
- BASEURL
= specifies the location from where the original ZIP files of the EPMBBS
  package (epm603.zip and epm603b.zip) are to be downloaded from.
.
.
[=NOTE]
.ul compact
  - It will generally not be necessary to modify that value !
  - You can predefine that value also as an environment variable before calling *nmake*
.el
- ZIPSRCDIR
= specifies a directory of your choice either empty or already holding
  the ZIP files of the EPMBBS package (epm603.zip and epm603b.zip).
  If files are not present, they are downloaded from LEO
  from the base URL - see setting BASEURL above.
.
.
[=NOTE]
.ul compact
  - the directory may not exist, but at least directory above
    must exist (that is not tested for !)
  - if you don't modify the value, the directory *zip* is created within your
    working directory and used for that purpose
  - You can predefine that value also as an environment variable before calling *nmake*
.el
- UNZIPPEDDIR
= specifies an empty or non-existant directory of your choice where
  to put unpacked files
.
.
[=NOTE]
.ul compact
  - the directory may not exist, but at least directory above must exist
    (that is not tested for !)
  - if you don't modify the value, the directory *epm.packages* is created within your
    working directory and used for that purpose
  - the contents of that directory (if any) is completely deleted
    before unpacking the EPMBBS package files
  - You can predefine that value also as an environment variable before calling *nmake*
.el


_*values to be configured by maintainer only*_
.pl bold
- STEM
= specifies the id of the project, used within some filenames
- VERSION
= specifies the current version, used in the name of the WPI package file
.
.
[=NOTE]
.ul compact
.at hi
  - modifying this version number does not currently automatically modify the
    version number used within the *WarpIn* script file! These have also to be modified
    accordingly.
.at
.el

.include guide.inc

