.. ***************************** Module Header *******************************
..
.. Module Name: titleeng.inc
..
.. Include file defining major variables for sources for INF files.
.. Requires HyperText/2 package to compile.
..
.. Copyright (c) Netlabs EPM Distribution Project 2002
..
.. $Id: titleeng.inc,v 1.6 2008-11-13 09:30:46 cla Exp $
..
.. ===========================================================================
..
.. This file is part of the Netlabs EPM Distribution package and is free
.. software.  You can redistribute it and/or modify it under the terms of the
.. GNU General Public License as published by the Free Software
.. Foundation, in version 2 as it comes in the "COPYING" file of the
.. Netlabs EPM Distribution.  This library is distributed in the hope that it
.. will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
.. of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.. General Public License for more details.
..
.. ***************************************************************************

.set DOCTITLE=netlabs.org EPM Distribution
.set USRTITLE=[=DOCTITLE] User's Guide
.set PRGTITLE=[=DOCTITLE] Programming Guide
.set FLDTITLE=[=DOCTITLE] Folder Help
.set DISTDIR=netlabs
.set USERDIR=myepm

.set TOPICS=Select one of the following topics:

.set YEAR=2002-2008
.set EMAIL=cla@clanganke.de

.set TITLE=*[=DOCTITLE]*

.set NOTE=*Note:*
.set WARNING=*Warning:*

